<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Description>This package adds a BinDate to CK.tUser and the sUserArchive/sUserRestore procedures (soft-delete / recycle bin for users).</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.DB.Actor" Version="28.0.3" />
    <PackageReference Include="CK.SqlServer.Transaction" Version="12.0.2" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="**\*.sql;**\*.tql;**\*.y4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CK.IO.User.BinnedUser\CK.IO.User.BinnedUser.csproj" />
  </ItemGroup>
</Project>
